# College Dataset

In [1]:
from ISLP import load_data
import pandas as pd
import numpy as np
college = load_data("College")
college

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,No,2197,1515,543,4,26,3089,2029,6797,3900,500,1200,60,60,21.0,14,4469,40
773,Yes,1959,1805,695,24,47,2849,1107,11520,4960,600,1250,73,75,13.3,31,9189,83
774,Yes,2097,1915,695,34,61,2793,166,6900,4200,617,781,67,75,14.4,20,8323,49
775,Yes,10705,2453,1317,95,99,5217,83,19840,6510,630,2115,96,96,5.8,49,40386,99
776,Yes,2989,1855,691,28,63,2988,1726,4990,3560,500,1250,75,75,18.1,28,4509,99

In [2]:
college.isna().sum()

Private        0
Apps           0
Accept         0
Enroll         0
Top10perc      0
Top25perc      0
F.Undergrad    0
P.Undergrad    0
Outstate       0
Room.Board     0
Books          0
Personal       0
PhD            0
Terminal       0
S.F.Ratio      0
perc.alumni    0
Expend         0
Grad.Rate      0
dtype: int64

In [3]:
college.dtypes

Private        category
Apps              int64
Accept            int64
Enroll            int64
Top10perc         int64
Top25perc         int64
F.Undergrad       int64
P.Undergrad       int64
Outstate          int64
Room.Board        int64
Books             int64
Personal          int64
PhD               int64
Terminal          int64
S.F.Ratio       float64
perc.alumni       int64
Expend            int64
Grad.Rate         int64
dtype: object

In [4]:
# Converting the feature Private from Yes/No to 0/1
college["Private"].unique()

['Yes', 'No']
Categories (2, object): ['No', 'Yes']

In [5]:
college["Private"] = college["Private"].map({'Yes':1, 'No':0})

# (a)

In [6]:
import sklearn.model_selection as skm
train, test = skm.train_test_split(college, test_size=0.25, shuffle=True, random_state=1)

In [7]:
test

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
374,1,594,385,307,36,57,1695,721,5580,2830,600,700,77,79,16.5,18,6170,61
491,1,1046,824,284,21,45,1223,451,10880,5050,400,1235,64,64,19.3,24,7344,69
678,0,1401,1239,605,10,34,3716,675,7100,4380,540,2948,63,88,19.4,0,5389,36
720,1,5661,2392,903,75,88,3499,172,13850,4360,500,1250,95,97,4.3,37,41766,89
412,0,10634,7064,3176,39,78,16505,5481,8400,6540,600,1300,92,98,17.5,21,9670,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,1,2100,1883,553,29,65,1704,1,16240,4690,500,500,84,96,11.1,43,14140,69
218,0,5653,4326,1727,17,29,9528,3822,10800,4840,580,1050,93,96,19.3,7,6751,46
467,1,1771,1325,306,21,46,1071,27,13840,3735,400,900,77,80,10.7,38,11080,74
118,0,8065,5257,2301,37,65,11755,770,8116,3610,800,1618,82,88,18.0,17,7597,73
201,0,3306,2079,1071,42,89,10208,9310,6597,2494,800,3028,81,96,13.9,20,6722,66

In [8]:
train

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
195,0,1801,1101,438,14,50,3065,363,6297,4600,600,1323,75,78,18.1,14,8355,68
320,0,3570,2215,651,17,41,3390,325,7352,3620,225,500,47,55,16.1,14,6374,63
757,1,1121,926,372,43,70,1270,160,12660,4500,678,2424,80,80,16.9,20,8328,80
34,1,1690,1366,662,30,61,2718,1460,10995,4410,1000,1000,68,74,17.6,20,8086,85
487,1,897,718,276,12,48,1345,390,10450,4020,500,1500,56,56,14.1,16,7444,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,1,1470,900,287,20,49,1130,417,10900,5100,500,550,70,81,15.7,14,7804,68
767,0,2320,1805,769,24,61,3395,670,6400,3392,580,2150,71,80,12.8,26,6729,59
72,1,6548,3813,862,49,85,3316,31,18550,4750,800,1200,95,97,14.2,36,13675,93
235,1,608,494,176,10,31,649,314,8330,3770,550,1300,64,80,13.0,31,7949,39
37,1,2496,1402,531,53,95,2121,69,17926,8124,600,850,83,93,10.3,33,12580,91

In [9]:
X_train, Y_train = train.drop(columns = ["Apps"]), train["Apps"]
X_test, Y_test = test.drop(columns = ["Apps"]), test["Apps"]

# (b)

In [10]:
import sklearn.linear_model as skl
model = skl.LinearRegression()
model.fit(X_train, Y_train)
Y_predicted = model.predict(X_test)

In [11]:
from sklearn import metrics
metrics.mean_squared_error(Y_test, Y_predicted)

636075.2934902587

# (c)

In [12]:
lambdas = np.logspace(-3, 3, 100)

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
scaler = StandardScaler(with_mean=True, with_std=True)
ridge = skl.RidgeCV(alphas=lambdas)
pipe = Pipeline(steps=[('scaler', scaler), ('ridge', ridge)])
pipe.fit(X_train, Y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('ridge',
                 RidgeCV(alphas=array([1.00000000e-03, 1.14975700e-03, 1.32194115e-03, 1.51991108e-03,
       1.74752840e-03, 2.00923300e-03, 2.31012970e-03, 2.65608778e-03,
       3.05385551e-03, 3.51119173e-03, 4.03701726e-03, 4.64158883e-03,
       5.33669923e-03, 6.13590727e-03, 7.05480231e-03, 8.11130831e-03,
       9.32603347e-03, 1.07226722e-02, 1.232...
       4.03701726e+01, 4.64158883e+01, 5.33669923e+01, 6.13590727e+01,
       7.05480231e+01, 8.11130831e+01, 9.32603347e+01, 1.07226722e+02,
       1.23284674e+02, 1.41747416e+02, 1.62975083e+02, 1.87381742e+02,
       2.15443469e+02, 2.47707636e+02, 2.84803587e+02, 3.27454916e+02,
       3.76493581e+02, 4.32876128e+02, 4.97702356e+02, 5.72236766e+02,
       6.57933225e+02, 7.56463328e+02, 8.69749003e+02, 1.00000000e+03])))])

In [14]:
pipe['ridge'].alpha_

np.float64(0.001)

In [15]:
Y_predicted_ridge = pipe.predict(X_test)
metrics.mean_squared_error(Y_test, Y_predicted_ridge)

636078.0813920484

# (d)

In [16]:
lasso = skl.LassoCV(alphas=lambdas)
pipe = Pipeline(steps=[('scaler', scaler), ('lasso', lasso)])
pipe.fit(X_train, Y_train)
print(pipe['lasso'].alpha_)
Y_predicted_lasso = pipe.predict(X_test)
print(metrics.mean_squared_error(Y_test, Y_predicted_lasso))

20.09233002565046
703984.5671028959

In [17]:
pd.DataFrame(pipe['lasso'].coef_, index=X_test.columns)

                       0
Private      -107.329713
Accept       3562.360093
Enroll        -74.051609
Top10perc     654.270324
Top25perc     -95.557199
F.Undergrad    -0.000000
P.Undergrad     0.000000
Outstate     -298.424324
Room.Board    165.877620
Books           0.000000
Personal        0.000000
PhD           -94.142058
Terminal      -38.651041
S.F.Ratio      29.259261
perc.alumni    -2.178585
Expend        407.937676
Grad.Rate      94.002738

In [18]:
np.count_nonzero(pipe['lasso'].coef_)

np.int64(13)

# (e)

In [27]:
from sklearn.decomposition import PCA
pcr_pipe = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('pca', PCA()),
    ('linear', skl.LinearRegression())
])
param_grid = {'pca__n_components': range(1, len(X_train.columns) + 1)}
grid = skm.GridSearchCV(
    pcr_pipe,
    param_grid,
    scoring='neg_mean_squared_error',
    cv=5
)
grid.fit(X_train, Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('pca', PCA()),
                                       ('linear', LinearRegression())]),
             param_grid={'pca__n_components': range(1, 18)},
             scoring='neg_mean_squared_error')

In [28]:
grid.best_params_

{'pca__n_components': 17}

In [29]:
Y_pred_pcr = grid.predict(X_test)
metrics.mean_squared_error(Y_test, Y_pred_pcr)

636075.2934902646

# (f)

In [31]:
from sklearn.cross_decomposition import PLSRegression
param_grid = {'pls__n_components': range(1, len(X_train.columns) + 1)}
pls_pipe = Pipeline(steps=[('scaler', scaler), ('pls', PLSRegression())])
grid_pls = skm.GridSearchCV(pls_pipe, param_grid, cv = 5)
grid_pls.fit(X_train, Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('pls', PLSRegression())]),
             param_grid={'pls__n_components': range(1, 18)})

In [32]:
grid_pls.best_params_

{'pls__n_components': 17}

In [33]:
Y_pred_pls = grid.predict(X_test)
metrics.mean_squared_error(Y_test, Y_pred_pls)

636075.2934902646

# (g)

Based on the mean squared error observation it is clear, that only Lasso has different error (higher) than other methods.
Since the PCR and PLS didn't reduce the dimension the it looks like all the dimensions are somewhat relevent to the data.
Lasso higher test error suggests that it removed (shrinked) the variable that contained predictive information.
So, we can suggest that the Linear Regression itself is the obvious choice, since it is simple and also explains the data better.