In [1]:
import numpy as np
import pandas as pd

In [2]:
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize)
from ISLP import confusion_table

In [3]:
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

# Default Dataset

In [4]:
default = load_data("Default")
default

     default student      balance        income
0         No      No   729.526495  44361.625074
1         No     Yes   817.180407  12106.134700
2         No      No  1073.549164  31767.138947
3         No      No   529.250605  35704.493935
4         No      No   785.655883  38463.495879
...      ...     ...          ...           ...
9995      No      No   711.555020  52992.378914
9996      No      No   757.962918  19660.721768
9997      No      No   845.411989  58636.156984
9998      No      No  1569.009053  36669.112365
9999      No     Yes   200.922183  16862.952321

[10000 rows x 4 columns]

# (a)

In [5]:
design = MS(["balance", "income"])
X = design.fit_transform(default)
y = default["default"] == "Yes"
model = sm.GLM(y, X, family=sm.families.Binomial())
results = model.fit()

In [6]:
summarize(results)

                coef   std err       z  P>|z|
intercept -11.540500  0.435000 -26.544    0.0
balance     0.005600  0.000000  24.835    0.0
income      0.000021  0.000005   4.174    0.0

# (b)

In [7]:
# (i)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
# (ii)
model_b = sm.GLM(y_train, X_train, family=sm.families.Binomial())
results_b = model_b.fit()
summarize(results_b)

                coef   std err       z  P>|z|
intercept -11.807100  0.551000 -21.417  0.000
balance     0.005900  0.000000  20.190  0.000
income      0.000018  0.000006   2.941  0.003

In [9]:
# (iii)
predictions = results_b.predict(X_test)
labels = np.where(predictions > 0.5, 1, 0)

In [10]:
# (iv)
np.sum(labels != y_test)/y_test.shape[0] * 100

np.float64(2.696969696969697)

In [11]:
confusion_table(labels, y_test)

Truth      False  True
Predicted
False       3178     77
True          12     33

# (c)

In [14]:
for random_state in [18, 25, 29]:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=random_state)
    model = sm.GLM(y_train, X_train, family=sm.families.Binomial())
    results = model.fit()
    print("\n Summary :", "\n", summarize(results), "\n")
    predictions = results.predict(X_test)
    labels = np.where(predictions > 0.5, 1, 0)
    print("validation set error:", np.sum(labels != y_test)/y_test.shape[0] * 100, "%")
    print(confusion_table(labels, y_test))

 Summary :
                 coef   std err       z  P>|z|
intercept -11.063400  0.506000 -21.858  0.000
balance     0.005400  0.000000  20.262  0.000
income      0.000019  0.000006   3.272  0.001

validation set error: 2.393939393939394 %
Truth      False  True
Predicted
False       3181     68
True          11     40

 Summary :
                 coef   std err       z  P>|z|
intercept -11.612800  0.533000 -21.790  0.000
balance     0.005800  0.000000  20.492  0.000
income      0.000018  0.000006   2.947  0.003

validation set error: 2.727272727272727 %
Truth      False  True
Predicted
False       3175     70
True          20     35

 Summary :
                 coef   std err       z  P>|z|
intercept -11.604500  0.526000 -22.069    0.0
balance     0.005600  0.000000  20.394    0.0
income      0.000028  0.000006   4.780    0.0

validation set error: 2.5757575757575757 %
Truth      False  True
Predicted
False       3181     69
True          16     34

Validation error fluctuates slightly depending on the random split.

# (d)

In [15]:
design = MS(["balance", "income", "student"])
X = design.fit_transform(default)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
model = sm.GLM(y_train, X_train, family=sm.families.Binomial())
results = model.fit()
summarize(results)

                      coef  std err       z  P>|z|
intercept    -1.114640e+01  0.62100 -17.937  0.000
balance       5.900000e-03  0.00000  20.099  0.000
income        5.117000e-07  0.00001   0.050  0.960
student[Yes] -6.344000e-01  0.29100  -2.178  0.029

In [17]:
predictions = results.predict(X_test)
labels = np.where(predictions > 0.5, 1, 0)
np.sum(labels != y_test)/y_test.shape[0] * 100

np.float64(2.727272727272727)

In [18]:
confusion_table(labels, y_test)

Truth      False  True
Predicted
False       3177     77
True          13     33

No, there is not much evidence that including the student variable lead to decrease in the validation test error rate. (Infact there is somewhat increase in the validation error rate)