In [1]:
import pandas as pd
import numpy as np

In [2]:
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize)

In [3]:
import statsmodels.api as sm

# Credit Card Default Dataset

In [4]:
default = load_data("Default")
default

     default student      balance        income
0         No      No   729.526495  44361.625074
1         No     Yes   817.180407  12106.134700
2         No      No  1073.549164  31767.138947
3         No      No   529.250605  35704.493935
4         No      No   785.655883  38463.495879
...      ...     ...          ...           ...
9995      No      No   711.555020  52992.378914
9996      No      No   757.962918  19660.721768
9997      No      No   845.411989  58636.156984
9998      No      No  1569.009053  36669.112365
9999      No     Yes   200.922183  16862.952321

[10000 rows x 4 columns]

# (a)

In [5]:
design = MS(["balance", "income"])
X = design.fit_transform(default)
y = default["default"] == "Yes"
model = sm.GLM(y, X, family=sm.families.Binomial())
results = model.fit()
summarize(results)

                coef   std err       z  P>|z|
intercept -11.540500  0.435000 -26.544    0.0
balance     0.005600  0.000000  24.835    0.0
income      0.000021  0.000005   4.174    0.0

In [11]:
results.params

intercept   -11.540468
balance       0.005647
income        0.000021
dtype: float64

# (b)

In [14]:
def boot_fn(data, idx):
    design = MS(["balance", "income"])
    X = design.fit_transform(data.iloc[idx])
    y = data.iloc[idx]["default"] == "Yes"
    model = sm.GLM(y, X, family=sm.families.Binomial())
    results = model.fit()
    return results.params

# (c)

In [25]:
rng = np.random.default_rng(1)
B = 1000 # no. of bootstrap sample
coefs = []
for _ in range(B):
    idx = rng.choice(default.shape[0], default.shape[0], replace=True)
    params = boot_fn(default, idx)
    coefs.append(params)
coefs

[intercept   -11.691159
 balance       0.005789
 income        0.000018
 dtype: float64,
 intercept   -11.913753
 balance       0.005711
 income        0.000027
 dtype: float64,
 intercept   -11.018952
 balance       0.005575
 income        0.000009
 dtype: float64,
 intercept   -11.537299
 balance       0.005588
 income        0.000027
 dtype: float64,
 intercept   -11.176961
 balance       0.005462
 income        0.000017
 dtype: float64,
 intercept   -11.817188
 balance       0.005857
 income        0.000020
 dtype: float64,
 intercept   -12.161960
 balance       0.005816
 income        0.000032
 dtype: float64,
 intercept   -12.421179
 balance       0.006096
 income        0.000025
 dtype: float64,
 intercept   -11.163702
 balance       0.005376
 income        0.000022
 dtype: float64,
 intercept   -11.345740
 balance       0.005603
 income        0.000017
 dtype: float64,
 intercept   -12.705349
 balance       0.006154
 income        0.000032
 dtype: float64,
 intercept   -11.433649
 balance       0.005678
 income        0.000017
 dtype: float64,
 intercept   -11.432680
 balance       0.005520
 income        0.000024
 dtype: float64,
 intercept   -12.140977
 balance       0.006005
 income        0.000023
 dtype: float64,
 intercept   -10.619728
 balance       0.005304
 income        0.000007
 dtype: float64,
 intercept   -11.382241
 balance       0.005658
 income        0.000015
 dtype: float64,
 intercept   -11.890245
 balance       0.005816
 income        0.000021
 dtype: float64,
 intercept   -11.311409
 balance       0.005546
 income        0.000023
 dtype: float64,
 intercept   -11.139211
 balance       0.005505
 income        0.000015
 dtype: float64,
 intercept   -11.805307
 balance       0.005804
 income        0.000020
 dtype: float64,
 intercept   -11.497847
 balance       0.005574
 income        0.000021
 dtype: float64,
 intercept   -11.473526
 balance       0.005519
 income        0.000023
 dtype: float64,
 intercept   -12.102797
 balance       0.005856
 income        0.000031
 dtype: float64,
 intercept   -11.484293
 balance       0.005543
 income        0.000025
 dtype: float64,
 intercept   -11.399851
 balance       0.005639
 income        0.000021
 dtype: float64,
 intercept   -12.091663
 balance       0.005925
 income        0.000022
 dtype: float64,
 intercept   -11.033562
 balance       0.005327
 income        0.000019
 dtype: float64,
 intercept   -11.167005
 balance       0.005469
 income        0.000018
 dtype: float64,
 intercept   -11.971136
 balance       0.005684
 income        0.000028
 dtype: float64,
 intercept   -11.103485
 balance       0.005523
 income        0.000015
 dtype: float64,
 intercept   -10.997561
 balance       0.005402
 income        0.000016
 dtype: float64,
 intercept   -11.519226
 balance       0.005608
 income        0.000023
 dtype: float64,
 intercept   -11.504506
 balance       0.005648
 income        0.000019
 dtype: float64,
 intercept   -11.225421
 balance       0.005424
 income        0.000020
 dtype: float64,
 intercept   -11.639958
 balance       0.005687
 income        0.000021
 dtype: float64,
 intercept   -11.195076
 balance       0.005471
 income        0.000020
 dtype: float64,
 intercept   -11.907041
 balance       0.005740
 income        0.000028
 dtype: float64,
 intercept   -12.138427
 balance       0.005925
 income        0.000028
 dtype: float64,
 intercept   -11.582226
 balance       0.005705
 income        0.000019
 dtype: float64,
 intercept   -11.160408
 balance       0.005392
 income        0.000020
 dtype: float64,
 intercept   -11.255073
 balance       0.005486
 income        0.000020
 dtype: float64,
 intercept   -11.557609
 balance       0.005569
 income        0.000024
 dtype: float64,
 intercept   -12.157861
 balance       0.005871
 income        0.000022
 dtype: float64,
 intercept   -11.887864
 balance       0.005860
 income        0.000023
 dtype: float64,
 intercept   -11.872164
 balance       0.005758
 income        0.000027
 dtype: float64,
 intercept   -11.078625
 balance       0.005516
 income        0.000014
 dtype: float64,
 intercept   -10.927431
 balance       0.005418
 income        0.000016
 dtype: float64,
 intercept   -11.412615
 balance       0.005544
 income        0.000022
 dtype: float64,
 intercept   -12.027331
 balance       0.005943
 income        0.000018
 dtype: float64,
 intercept   -12.333173
 balance       0.005923
 income        0.000030
 dtype: float64,
 intercept   -11.913150
 balance       0.005843
 income        0.000025
 dtype: float64,
 intercept   -11.372206
 balance       0.005530
 income        0.000023
 dtype: float64,
 intercept   -11.397408
 balance       0.005695
 income        0.000017
 dtype: float64,
 intercept   -11.812660
 balance       0.005640
 income        0.000029
 dtype: float64,
 intercept   -11.851200
 balance       0.005917
 income        0.000023
 dtype: float64,
 intercept   -11.348292
 balance       0.005496
 income        0.000022
 dtype: float64,
 intercept   -11.961081
 balance       0.005925
 income        0.000017
 dtype: float64,
 intercept   -12.126092
 balance       0.006034
 income        0.000021
 dtype: float64,
 intercept   -12.410787
 balance       0.005914
 income        0.000031
 dtype: float64,
 intercept   -11.359979
 balance       0.005668
 income        0.000015
 dtype: float64,
 intercept   -11.305665
 balance       0.005418
 income        0.000026
 dtype: float64,
 intercept   -11.863554
 balance       0.005797
 income        0.000022
 dtype: float64,
 intercept   -11.751234
 balance       0.005729
 income        0.000023
 dtype: float64,
 intercept   -12.835518
 balance       0.006250
 income        0.000028
 dtype: float64,
 intercept   -11.231479
 balance       0.005509
 income        0.000019
 dtype: float64,
 intercept   -12.126788
 balance       0.005828
 income        0.000027
 dtype: float64,
 intercept   -10.912230
 balance       0.005424
 income        0.000016
 dtype: float64,
 intercept   -11.784597
 balance       0.005715
 income        0.000024
 dtype: float64,
 intercept   -11.785010
 balance       0.005711
 income        0.000028
 dtype: float64,
 intercept   -11.265434
 balance       0.005617
 income        0.000017
 dtype: float64,
 intercept   -11.971895
 balance       0.005982
 income        0.000018
 dtype: float64,
 intercept   -11.857212
 balance       0.005779
 income        0.000025
 dtype: float64,
 intercept   -11.656338
 balance       0.005725
 income        0.000022
 dtype: float64,
 intercept   -12.118420
 balance       0.005937
 income        0.000025
 dtype: float64,
 intercept   -11.110673
 balance       0.005563
 income        0.000012
 dtype: float64,
 intercept   -11.447094
 balance       0.005700
 income        0.000015
 dtype: float64,
 intercept   -11.770300
 balance       0.005720
 income        0.000021
 dtype: float64,
 intercept   -10.634352
 balance       0.005297
 income        0.000014
 dtype: float64,
 intercept   -12.126339
 balance       0.005872
 income        0.000023
 dtype: float64,
 intercept   -10.675802
 balance       0.005162
 income        0.000017
 dtype: float64,
 intercept   -11.278895
 balance       0.005563
 income        0.000015
 dtype: float64,
 intercept   -11.635868
 balance       0.005658
 income        0.000023
 dtype: float64,
 intercept   -10.961327
 balance       0.005446
 income        0.000015
 dtype: float64,
 intercept   -11.626289
 balance       0.005748
 income        0.000018
 dtype: float64,
 intercept   -11.363353
 balance       0.005694
 income        0.000013
 dtype: float64,
 intercept   -11.374595
 balance       0.005685
 income        0.000014
 dtype: float64,
 intercept   -11.808367
 balance       0.005850
 income        0.000019
 dtype: float64,
 intercept   -11.792508
 balance       0.005624
 income        0.000029
 dtype: float64,
 intercept   -10.924779
 balance       0.005313
 income        0.000019
 dtype: float64,
 intercept   -12.578554
 balance       0.006378
 income        0.000017
 dtype: float64,
 intercept   -10.979695
 balance       0.005368
 income        0.000020
 dtype: float64,
 intercept   -11.573872
 balance       0.005527
 income        0.000025
 dtype: float64,
 intercept   -12.257892
 balance       0.006033
 income        0.000022
 dtype: float64,
 intercept   -11.304837
 balance       0.005388
 income        0.000027
 dtype: float64,
 intercept   -10.443059
 balance       0.005059
 income        0.000013
 dtype: float64,
 intercept   -11.732208
 balance       0.005707
 income        0.000026
 dtype: float64,
 intercept   -11.456703
 balance       0.005626
 income        0.000022
 dtype: float64,
 intercept   -11.802650
 balance       0.005681
 income        0.000028
 dtype: float64,
 intercept   -11.138403
 balance       0.005365
 income        0.000022
 dtype: float64,
 intercept   -11.452205
 balance       0.005613
 income        0.000019
 dtype: float64,
 intercept   -12.237747
 balance       0.006053
 income        0.000019
 dtype: float64,
 intercept   -10.832613
 balance       0.005231
 income        0.000015
 dtype: float64,
 intercept   -11.644190
 balance       0.005674
 income        0.000022
 dtype: float64,
 intercept   -11.255300
 balance       0.005668
 income        0.000012
 dtype: float64,
 intercept   -12.104066
 balance       0.005979
 income        0.000022
 dtype: float64,
 intercept   -12.147176
 balance       0.006042
 income        0.000020
 dtype: float64,
 intercept   -11.488860
 balance       0.005706
 income        0.000016
 dtype: float64,
 intercept   -11.299728
 balance       0.005395
 income        0.000022
 dtype: float64,
 intercept   -12.624570
 balance       0.006456
 income        0.000018
 dtype: float64,
 intercept   -11.507811
 balance       0.005575
 income        0.000021
 dtype: float64,
 intercept   -11.016626
 balance       0.005455
 income        0.000015
 dtype: float64,
 intercept   -11.858413
 balance       0.005846
 income        0.000022
 dtype: float64,
 intercept   -11.52237
 balance       0.00565
 income        0.00002
 dtype: float64,
 intercept   -12.713014
 balance       0.006291
 income        0.000018
 dtype: float64,
 intercept   -11.379207
 balance       0.005381
 income        0.000030
 dtype: float64,
 intercept   -11.096870
 balance       0.005494
 income        0.000017
 dtype: float64,
 intercept   -11.931099
 balance       0.005776
 income        0.000022
 dtype: float64,
 intercept   -10.641673
 balance       0.005241
 income        0.000012
 dtype: float64,
 intercept   -11.610476
 balance       0.005594
 income        0.000023
 dtype: float64,
 intercept   -12.236910
 balance       0.006061
 income        0.000022
 dtype: float64,
 intercept   -11.399432
 balance       0.005406
 income        0.000022
 dtype: float64,
 intercept   -11.211074
 balance       0.005590
 income        0.000017
 dtype: float64,
 intercept   -10.979214
 balance       0.005445
 income        0.000015
 dtype: float64,
 intercept   -10.506105
 balance       0.005215
 income        0.000015
 dtype: float64,
 intercept   -11.517295
 balance       0.005633
 income        0.000025
 dtype: float64,
 intercept   -11.476809
 balance       0.005408
 income        0.000027
 dtype: float64,
 intercept   -11.802042
 balance       0.005693
 income        0.000028
 dtype: float64,
 intercept   -11.872874
 balance       0.005761
 income        0.000025
 dtype: float64,
 intercept   -11.445668
 balance       0.005468
 income        0.000027
 dtype: float64,
 intercept   -11.581864
 balance       0.005638
 income        0.000024
 dtype: float64,
 intercept   -11.776851
 balance       0.005757
 income        0.000022
 dtype: float64,
 intercept   -11.764670
 balance       0.005609
 income        0.000030
 dtype: float64,
 intercept   -10.931887
 balance       0.005297
 income        0.000018
 dtype: float64,
 intercept   -12.343843
 balance       0.006004
 income        0.000025
 dtype: float64,
 intercept   -10.604534
 balance       0.005347
 income        0.000009
 dtype: float64,
 intercept   -11.038028
 balance       0.005384
 income        0.000018
 dtype: float64,
 intercept   -11.015246
 balance       0.005485
 income        0.000015
 dtype: float64,
 intercept   -11.267785
 balance       0.005584
 income        0.000015
 dtype: float64,
 intercept   -11.638410
 balance       0.005758
 income        0.000019
 dtype: float64,
 intercept   -11.590246
 balance       0.005734
 income        0.000018
 dtype: float64,
 intercept   -12.397154
 balance       0.006013
 income        0.000030
 dtype: float64,
 intercept   -11.496726
 balance       0.005619
 income        0.000023
 dtype: float64,
 intercept   -11.609464
 balance       0.005695
 income        0.000020
 dtype: float64,
 intercept   -12.236289
 balance       0.006044
 income        0.000026
 dtype: float64,
 intercept   -12.583420
 balance       0.006249
 income        0.000025
 dtype: float64,
 intercept   -12.037750
 balance       0.005877
 income        0.000023
 dtype: float64,
 intercept   -11.947917
 balance       0.005895
 income        0.000025
 dtype: float64,
 intercept   -11.140375
 balance       0.005643
 income        0.000012
 dtype: float64,
 intercept   -11.616760
 balance       0.005771
 income        0.000021
 dtype: float64,
 intercept   -11.524100
 balance       0.005474
 income        0.000029
 dtype: float64,
 intercept   -10.891511
 balance       0.005350
 income        0.000016
 dtype: float64,
 intercept   -10.994218
 balance       0.005317
 income        0.000022
 dtype: float64,
 intercept   -11.042927
 balance       0.005439
 income        0.000017
 dtype: float64,
 intercept   -11.371382
 balance       0.005570
 income        0.000022
 dtype: float64,
 intercept   -12.263958
 balance       0.005881
 income        0.000029
 dtype: float64,
 intercept   -11.537174
 balance       0.005614
 income        0.000022
 dtype: float64,
 intercept   -11.819409
 balance       0.005752
 income        0.000026
 dtype: float64,
 intercept   -12.098006
 balance       0.005928
 income        0.000027
 dtype: float64,
 intercept   -11.716925
 balance       0.005771
 income        0.000019
 dtype: float64,
 intercept   -11.279625
 balance       0.005509
 income        0.000020
 dtype: float64,
 intercept   -12.132352
 balance       0.006053
 income        0.000019
 dtype: float64,
 intercept   -11.065806
 balance       0.005403
 income        0.000018
 dtype: float64,
 intercept   -11.256686
 balance       0.005469
 income        0.000025
 dtype: float64,
 intercept   -12.340203
 balance       0.005985
 income        0.000030
 dtype: float64,
 intercept   -11.917894
 balance       0.005657
 income        0.000031
 dtype: float64,
 intercept   -10.972480
 balance       0.005322
 income        0.000019
 dtype: float64,
 intercept   -11.516820
 balance       0.005456
 income        0.000027
 dtype: float64,
 intercept   -11.803617
 balance       0.005888
 income        0.000019
 dtype: float64,
 intercept   -11.750770
 balance       0.005676
 income        0.000027
 dtype: float64,
 intercept   -12.275713
 balance       0.005957
 income        0.000025
 dtype: float64,
 intercept   -11.061771
 balance       0.005335
 income        0.000023
 dtype: float64,
 intercept   -11.440417
 balance       0.005723
 income        0.000013
 dtype: float64,
 intercept   -12.267937
 balance       0.005921
 income        0.000031
 dtype: float64,
 intercept   -12.121120
 balance       0.006050
 income        0.000017
 dtype: float64,
 intercept   -11.449074
 balance       0.005516
 income        0.000022
 dtype: float64,
 intercept   -11.414660
 balance       0.005539
 income        0.000020
 dtype: float64,
 intercept   -11.335667
 balance       0.005569
 income        0.000018
 dtype: float64,
 intercept   -11.231505
 balance       0.005503
 income        0.000017
 dtype: float64,
 intercept   -11.275066
 balance       0.005498
 income        0.000021
 dtype: float64,
 intercept   -11.190967
 balance       0.005455
 income        0.000023
 dtype: float64,
 intercept   -11.542225
 balance       0.005681
 income        0.000022
 dtype: float64,
 intercept   -12.283564
 balance       0.005882
 income        0.000032
 dtype: float64,
 intercept   -11.376067
 balance       0.005632
 income        0.000015
 dtype: float64,
 intercept   -11.615366
 balance       0.005789
 income        0.000019
 dtype: float64,
 intercept   -11.305957
 balance       0.005577
 income        0.000019
 dtype: float64,
 intercept   -12.397386
 balance       0.005952
 income        0.000030
 dtype: float64,
 intercept   -11.524971
 balance       0.005574
 income        0.000021
 dtype: float64,
 intercept   -11.429312
 balance       0.005588
 income        0.000021
 dtype: float64,
 intercept   -12.093423
 balance       0.005916
 income        0.000022
 dtype: float64,
 intercept   -11.749551
 balance       0.005739
 income        0.000027
 dtype: float64,
 intercept   -11.785182
 balance       0.005969
 income        0.000012
 dtype: float64,
 intercept   -12.070257
 balance       0.005903
 income        0.000025
 dtype: float64,
 intercept   -11.672228
 balance       0.005436
 income        0.000033
 dtype: float64,
 intercept   -11.408419
 balance       0.005569
 income        0.000020
 dtype: float64,
 intercept   -11.394751
 balance       0.005547
 income        0.000024
 dtype: float64,
 intercept   -11.661582
 balance       0.005747
 income        0.000020
 dtype: float64,
 intercept   -12.290714
 balance       0.005940
 income        0.000030
 dtype: float64,
 intercept   -11.730186
 balance       0.005700
 income        0.000023
 dtype: float64,
 intercept   -11.462734
 balance       0.005618
 income        0.000018
 dtype: float64,
 intercept   -11.447583
 balance       0.005553
 income        0.000021
 dtype: float64,
 intercept   -11.409569
 balance       0.005658
 income        0.000020
 dtype: float64,
 intercept   -11.587305
 balance       0.005679
 income        0.000020
 dtype: float64,
 intercept   -11.243619
 balance       0.005461
 income        0.000023
 dtype: float64,
 intercept   -11.472236
 balance       0.005477
 income        0.000025
 dtype: float64,
 intercept   -11.594426
 balance       0.005679
 income        0.000018
 dtype: float64,
 intercept   -11.926583
 balance       0.005905
 income        0.000018
 dtype: float64,
 intercept   -11.540292
 balance       0.005770
 income        0.000014
 dtype: float64,
 intercept   -10.993463
 balance       0.005351
 income        0.000016
 dtype: float64,
 intercept   -11.750288
 balance       0.005727
 income        0.000022
 dtype: float64,
 intercept   -12.384161
 balance       0.006078
 income        0.000020
 dtype: float64,
 intercept   -11.534359
 balance       0.005769
 income        0.000016
 dtype: float64,
 intercept   -10.954729
 balance       0.005372
 income        0.000016
 dtype: float64,
 intercept   -11.024716
 balance       0.005336
 income        0.000022
 dtype: float64,
 intercept   -11.629574
 balance       0.005669
 income        0.000024
 dtype: float64,
 intercept   -10.651432
 balance       0.005300
 income        0.000014
 dtype: float64,
 intercept   -11.823475
 balance       0.005774
 income        0.000022
 dtype: float64,
 intercept   -11.582253
 balance       0.005827
 income        0.000017
 dtype: float64,
 intercept   -12.290591
 balance       0.006070
 income        0.000024
 dtype: float64,
 intercept   -11.635070
 balance       0.005660
 income        0.000023
 dtype: float64,
 intercept   -12.232057
 balance       0.005998
 income        0.000024
 dtype: float64,
 intercept   -11.333030
 balance       0.005602
 income        0.000014
 dtype: float64,
 intercept   -11.449215
 balance       0.005649
 income        0.000021
 dtype: float64,
 intercept   -10.997848
 balance       0.005283
 income        0.000020
 dtype: float64,
 intercept   -11.201782
 balance       0.005376
 income        0.000024
 dtype: float64,
 intercept   -11.938696
 balance       0.005906

In [29]:
coefs = np.array(coefs)
np.std(coefs, axis=0)

array([4.38104183e-01, 2.25799772e-04, 4.87116546e-06])

# (d)

The SE calculated using bootstrap is very close to the actual SE given by sm.GLE method.